name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  push_to_registry:
    name: push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: login to docker
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build & push image
        uses: docker/build-push-action@v6.0.0
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/graffiti:latest
          build-args: |
            VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
            VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}
